# SwiftLint Configuration for Grain Project

# Paths to include for linting
included:
  - Grain/
  - GrainAI/

# Paths to exclude from linting
excluded:
  - Pods/
  - Carthage/
  - .build/
  - DerivedData/
  - fastlane/
  - Grain.app/

# Opt-in rules for better code quality
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call

# Disabled rules (config-specific)
disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
    error: 50

large_tuple:
  warning: 3
  error: 5

# Custom rules configuration
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\('
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

  # Force unwrapping is dangerous
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '!$'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping - use optional binding or guard"
    severity: error

  # TODO comments should be tracked
  todo_comments:
    name: "TODO Comments"
    regex: '(TODO|FIXME)'
    message: "TODO comments should be tracked in issue tracker"
    severity: warning
